/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;


import Menu.images.Authentification;
import classes.Compte;
import classes.commande;
import classes.produit;
import java.awt.Toolkit;
import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import panels.AjoutProd;
import panels.DashBoard;
import panels.GestionCommandes;
import static panels.GestionCommandes.initJcbCommande;
import static panels.GestionCommandes.listerCommande;
import panels.HomePanel;
import panels.GestionComptes;
import static panels.GestionComptes.initJcbCompte;
import static panels.GestionComptes.listerCompte;
import panels.GestionFournisseurs;
import panels.GestionProduits;
import static panels.GestionProduits.initJcbProd;
import static panels.GestionProduits.listerProduit;
import panels.InformationProd;
import static panels.InformationProd.initJcbinfoProd;
import panels.SupprimerCompte;



import panels.create;
import panels.supprimerPrd;








/**
 *
 * @author hp
 */
public class Menustat extends javax.swing.JFrame {

    public static void GProdPanelMouseClicked(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
   // private static ImageIcon ICON = new ImageIcon(Menustat.class.getResource("/icon.png"));
  

    /**
     * Creates new form Menustat
     */
    
    HomePanel p1 = new HomePanel();
    GestionComptes gc = new GestionComptes ();
    GestionCommandes gco = new  GestionCommandes();
    GestionProduits gp = new GestionProduits();
    GestionFournisseurs gf = new GestionFournisseurs();
    AjoutProd ajp =new  AjoutProd();
    InformationProd ip = new InformationProd();
     create cc = new create();
      supprimerPrd p = new  supprimerPrd();
        SupprimerCompte sc = new SupprimerCompte ();
       DashBoard d = new DashBoard();
       AjoutProd ap = new  AjoutProd();
     
    
    public Menustat() {
        initComponents();
        PanelPrinc.add(p1);
        PanelPrinc.add(gc);
        PanelPrinc.add(gco);
        PanelPrinc.add(gp);
        PanelPrinc.add(gf);
        PanelPrinc.add(ajp);
        PanelPrinc.add(ip);
        PanelPrinc.add(cc);
        PanelPrinc.add(p);
         PanelPrinc.add(sc);
         PanelPrinc.add(d);
          PanelPrinc.add(ap);
        
        
        p1.setVisible(true);
         gc.setVisible(false);
          gco.setVisible(false);
           gp.setVisible(false);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
            cc.setVisible(false);
            p.setVisible(false);
             sc.setVisible(false);
            d.setVisible(false);
            ap.setVisible(false);
         
      
      
    //setIconImage(ICON.getImage());

   

    }
   
    
  

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        GComptePanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        GComptePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        GFrsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GProdPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GcomPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        GcomPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NomAdmin = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PanelPrinc = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(255, 51, 51));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\admin.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        sidePane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        sidePane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        GComptePanel1.setBackground(new java.awt.Color(255, 255, 255));
        GComptePanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GComptePanel1MouseMoved(evt);
            }
        });
        GComptePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GComptePanel1MouseClicked(evt);
            }
        });
        GComptePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GComptePanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));
        GComptePanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 23, -1, 17));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\63-home-flat.gif")); // NOI18N
        jLabel21.setText("   HOME");
        GComptePanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, 30));
        GComptePanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, 20, 29));

        sidePane.add(GComptePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 50));

        GComptePanel.setBackground(new java.awt.Color(255, 255, 255));
        GComptePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GComptePanelMouseMoved(evt);
            }
        });
        GComptePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GComptePanelMouseClicked(evt);
            }
        });
        GComptePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GComptePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));
        GComptePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 23, -1, 17));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\profile.png")); // NOI18N
        jLabel4.setText("  Gestion des Comptes");
        GComptePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 10, 210, 30));
        GComptePanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, 20, 29));

        sidePane.add(GComptePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 50));

        GFrsPanel.setBackground(new java.awt.Color(255, 255, 255));
        GFrsPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GFrsPanelMouseMoved(evt);
            }
        });
        GFrsPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GFrsPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GFrsPanelMousePressed(evt);
            }
        });
        GFrsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GFrsPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 10, -1, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\puzzle.png")); // NOI18N
        jLabel5.setText("  Gestion des Fournisseurs");
        GFrsPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        sidePane.add(GFrsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, 50));

        GProdPanel.setBackground(new java.awt.Color(255, 255, 255));
        GProdPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GProdPanelMouseMoved(evt);
            }
        });
        GProdPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GProdPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GProdPanelMousePressed(evt);
            }
        });
        GProdPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GProdPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\delivery-box.png")); // NOI18N
        jLabel7.setText("   Gestion des Produits");
        GProdPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 30));

        sidePane.add(GProdPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 270, 50));

        GcomPanel.setBackground(new java.awt.Color(255, 255, 255));
        GcomPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GcomPanelMouseMoved(evt);
            }
        });
        GcomPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GcomPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GcomPanelMousePressed(evt);
            }
        });
        GcomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\verifier.png")); // NOI18N
        jLabel16.setText("  Gestion des Commandes");
        GcomPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        sidePane.add(GcomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, 50));

        GcomPanel1.setBackground(new java.awt.Color(255, 255, 255));
        GcomPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GcomPanel1MouseMoved(evt);
            }
        });
        GcomPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GcomPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GcomPanel1MousePressed(evt);
            }
        });
        GcomPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GcomPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\business-report.png")); // NOI18N
        jLabel9.setText("  DASHBOARD");
        GcomPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        sidePane.add(GcomPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 270, -1));

        NomAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NomAdmin.setForeground(new java.awt.Color(255, 255, 255));
        NomAdmin.setText(" ");
        NomAdmin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        sidePane.add(NomAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\technical-support (1).png")); // NOI18N
        sidePane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 30, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel13.setText("Support");
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel14.setText("Log-out");
        sidePane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\logout (3).png")); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        sidePane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\3227825.png")); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 204, 255)));
        sidePane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 484));

        Main.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 484));

        PanelPrinc.setLayout(new javax.swing.BoxLayout(PanelPrinc, javax.swing.BoxLayout.LINE_AXIS));
        Main.add(PanelPrinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 750, 460));

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void GComptePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GComptePanelMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
         gc.setVisible(true);
          gco.setVisible(false);
           gp.setVisible(false);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
              d.setVisible(false);
       
    }//GEN-LAST:event_GComptePanelMouseClicked

    private void GFrsPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GFrsPanelMouseClicked
        // TODO add your handling code here:
       p1.setVisible(false);
         gc.setVisible(false);
          gco.setVisible(false);
           gp.setVisible(false);
            gf.setVisible(true);
            ajp.setVisible(false);
            ip.setVisible(false);
              d.setVisible(false);
        
    }//GEN-LAST:event_GFrsPanelMouseClicked

    private void GProdPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GProdPanelMouseClicked
        // TODO add your handling code here:
      p1.setVisible(false);
         gc.setVisible(false);
          gco.setVisible(false);
           gp.setVisible(true);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
              d.setVisible(false);
            
    }//GEN-LAST:event_GProdPanelMouseClicked

    private void GcomPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMouseClicked
        // TODO add your handling code here:
         p1.setVisible(false);
         gc.setVisible(false);
          gco.setVisible(true);
           gp.setVisible(false);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
              d.setVisible(false);
       
    }//GEN-LAST:event_GcomPanelMouseClicked

    private void GProdPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GProdPanelMousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_GProdPanelMousePressed

    private void GFrsPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GFrsPanelMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_GFrsPanelMousePressed

    private void GcomPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_GcomPanelMousePressed

    private void GComptePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GComptePanelMouseMoved
        // TODO add your handling code here:
       
          jLabel4.setForeground(new java.awt.Color(51,204, 255));
           jLabel5.setForeground(new java.awt.Color(0,0, 0));
            jLabel7.setForeground(new java.awt.Color(0,0, 0));
             jLabel9.setForeground(new java.awt.Color(0,0, 0));
              jLabel16.setForeground(new java.awt.Color(0,0, 0));
                jLabel21.setForeground(new java.awt.Color(0,0, 0));
            
    }//GEN-LAST:event_GComptePanelMouseMoved

    private void GFrsPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GFrsPanelMouseMoved
        // TODO add your handling code here:
        // GFrsPanel.setBackground(new java.awt.Color(nb2,0, nb2));
         jLabel5.setForeground(new java.awt.Color(51,204, 255));
          jLabel4.setForeground(new java.awt.Color(0,0, 0));
            jLabel7.setForeground(new java.awt.Color(0,0, 0));
             jLabel9.setForeground(new java.awt.Color(0,0, 0));
              jLabel16.setForeground(new java.awt.Color(0,0, 0));
                jLabel21.setForeground(new java.awt.Color(0,0, 0));
         
    }//GEN-LAST:event_GFrsPanelMouseMoved

    private void GProdPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GProdPanelMouseMoved
        // TODO add your handling code here:
        //GProdPanel.setBackground(new java.awt.Color(nb2,0, nb2));
          jLabel7.setForeground(new java.awt.Color(51,204, 255));
           jLabel5.setForeground(new java.awt.Color(0,0, 0));
            jLabel4.setForeground(new java.awt.Color(0,0, 0));
             jLabel9.setForeground(new java.awt.Color(0,0, 0));
                         jLabel16.setForeground(new java.awt.Color(0,0, 0));
                           jLabel21.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GProdPanelMouseMoved

    private void GcomPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMouseMoved
        // TODO add your handling code here:
        // GcomPanel.setBackground(new java.awt.Color(nb2,0, nb2));
         jLabel16.setForeground(new java.awt.Color(51,204, 255));
          jLabel5.setForeground(new java.awt.Color(0,0, 0));
            jLabel7.setForeground(new java.awt.Color(0,0, 0));
             jLabel4.setForeground(new java.awt.Color(0,0, 0));
              jLabel19.setForeground(new java.awt.Color(0,0, 0));
               jLabel21.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GcomPanelMouseMoved

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        // p1.setVisible(true);
        // gc.setVisible(false);
          //gco.setVisible(false);
           //gp.setVisible(false);
            //gf.setVisible(false);
           // ajp.setVisible(false);
            //ip.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        this.hide();
        Authentification auth = new  Authentification();
        auth.setVisible(true);
        
    }//GEN-LAST:event_jLabel20MouseClicked

    private void GcomPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MouseMoved
        // TODO add your handling code here:
        jLabel9.setForeground(new java.awt.Color(51,204, 255));
          jLabel5.setForeground(new java.awt.Color(0,0, 0));
            jLabel7.setForeground(new java.awt.Color(0,0, 0));
             jLabel4.setForeground(new java.awt.Color(0,0, 0));
              jLabel16.setForeground(new java.awt.Color(0,0, 0));
               jLabel21.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GcomPanel1MouseMoved

    private void GcomPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MouseClicked
        // TODO add your handling code here:
         d.setVisible(true);
         p1.setVisible(false);
         gc.setVisible(false);
          gco.setVisible(false);
           gp.setVisible(false);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
            
    }//GEN-LAST:event_GcomPanel1MouseClicked

    private void GcomPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GcomPanel1MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       GestionComptes.listerCompte();
        GestionProduits.listerProduit(); 
       // listerCommande( evt);
      String login =Authentification.getlogin();
                NomAdmin.setText(login);
       initJcbCompte(evt);
       //listerWSupCompte(evt);
       
       initJcbProd(evt);
       initJcbCommande(evt);
       GestionFournisseurs.listerfrs(evt);
       
      
         int nb = Compte.nbrComptes();
    String nombre =Integer.toString(nb);
     DashBoard.nbuser.setText(nombre);
      int n = produit.nbrPrd();
    String nbr =Integer.toString(n);
     DashBoard.nbprd.setText(nbr);
      int nbc = commande.nbrCom();
    String nbcom =Integer.toString(nbc);
     DashBoard.labelCommande.setText(nbcom);
        
    }//GEN-LAST:event_formWindowOpened

    private void GComptePanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GComptePanel1MouseMoved
        // TODO add your handling code here:
        
        jLabel21.setForeground(new java.awt.Color(51,204, 255));
          jLabel5.setForeground(new java.awt.Color(0,0, 0));
            jLabel7.setForeground(new java.awt.Color(0,0, 0));
             jLabel4.setForeground(new java.awt.Color(0,0, 0));
              jLabel16.setForeground(new java.awt.Color(0,0, 0));
               jLabel9.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GComptePanel1MouseMoved

    private void GComptePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GComptePanel1MouseClicked
        // TODO add your handling code here:
        
         p1.setVisible(true);
         gc.setVisible(false);
          gco.setVisible(false);
           gp.setVisible(false);
            gf.setVisible(false);
            ajp.setVisible(false);
            ip.setVisible(false);
    }//GEN-LAST:event_GComptePanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menustat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menustat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menustat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menustat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Menustat().setVisible(true);
                 
               // HOME.setSelectedIndex(3);
           

                
                 
               
        
                
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GComptePanel;
    private javax.swing.JPanel GComptePanel1;
    private javax.swing.JPanel GFrsPanel;
    private javax.swing.JPanel GProdPanel;
    private javax.swing.JPanel GcomPanel;
    private javax.swing.JPanel GcomPanel1;
    private javax.swing.JPanel Main;
    public static javax.swing.JLabel NomAdmin;
    private javax.swing.JPanel PanelPrinc;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables

    

   
   
   
}
