/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import static Menu.Menustat.NomAdmin;
import Menu.images.Authentification;
import panels.AjoutProd;
import panels.DashClient;
import panels.GestionCommandes;
import panels.GestionCommandesClient;

import panels.HomePanel;
import panels.InformationProd;
import panels.effectueCom;


/**
 *
 * @author hp
 */
public class MenuClient extends javax.swing.JFrame {

    /**
     * Creates new form MenuClient
     */
    
    
     HomePanel p1 = new HomePanel();
    
    GestionCommandesClient gco = new  GestionCommandesClient();
    effectueCom ef = new   effectueCom(); 
    DashClient dc  = new DashClient();
    
    
    InformationProd ip = new InformationProd();
     
    public MenuClient() {
        initComponents();
        
         PanelPrinc.add(p1);
          PanelPrinc.add(ef);
       
        PanelPrinc.add(gco);
        PanelPrinc.add(dc);
       
        
        PanelPrinc.add(ip);
       
        
        
        p1.setVisible(true);
        
          gco.setVisible(false);
           dc.setVisible(false);
          
            ip.setVisible(false);
             ef.setVisible(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        sidePane = new javax.swing.JPanel();
        GcomPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        GcomPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        GcomPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nomclient = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PanelPrinc = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePane.setBackground(new java.awt.Color(255, 51, 51));
        sidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GcomPanel2.setBackground(new java.awt.Color(255, 255, 255));
        GcomPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GcomPanel2MouseMoved(evt);
            }
        });
        GcomPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GcomPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GcomPanel2MousePressed(evt);
            }
        });
        GcomPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\63-home-flat.gif")); // NOI18N
        jLabel21.setText(" HOME");
        GcomPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        sidePane.add(GcomPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 270, 50));

        GcomPanel.setBackground(new java.awt.Color(255, 255, 255));
        GcomPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GcomPanelMouseMoved(evt);
            }
        });
        GcomPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GcomPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GcomPanelMousePressed(evt);
            }
        });
        GcomPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\verifier.png")); // NOI18N
        jLabel16.setText("   COMMANDER");
        GcomPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        sidePane.add(GcomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 50));

        GcomPanel1.setBackground(new java.awt.Color(255, 255, 255));
        GcomPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GcomPanel1MouseMoved(evt);
            }
        });
        GcomPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GcomPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GcomPanel1MousePressed(evt);
            }
        });
        GcomPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        GcomPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\business-report.png")); // NOI18N
        jLabel9.setText("  DASHBOARD");
        GcomPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 30));

        sidePane.add(GcomPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 270, -1));

        Nomclient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nomclient.setForeground(new java.awt.Color(255, 255, 255));
        Nomclient.setText(" ");
        Nomclient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        sidePane.add(Nomclient, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 100, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Client");
        sidePane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\client.png")); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        sidePane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\technical-support (1).png")); // NOI18N
        sidePane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 30, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel13.setText("Support");
        sidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel14.setText("Log-out");
        sidePane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\logout (3).png")); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        sidePane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\3227825.png")); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(102, 204, 255)));
        sidePane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 484));

        Main.add(sidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 484));

        PanelPrinc.setLayout(new javax.swing.BoxLayout(PanelPrinc, javax.swing.BoxLayout.LINE_AXIS));
        Main.add(PanelPrinc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 720, 460));

        getContentPane().add(Main);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GcomPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMouseMoved
        // TODO add your handling code here:
        // GcomPanel.setBackground(new java.awt.Color(nb2,0, nb2));
        jLabel16.setForeground(new java.awt.Color(51,204, 255));
       
        jLabel9.setForeground(new java.awt.Color(0,0, 0));
        jLabel21.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GcomPanelMouseMoved

    private void GcomPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMouseClicked
        // TODO add your handling code here:
        p1.setVisible(false);
        
        gco.setVisible(true);

        ip.setVisible(false);
         dc.setVisible(false);

    }//GEN-LAST:event_GcomPanelMouseClicked

    private void GcomPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanelMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_GcomPanelMousePressed

    private void GcomPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MouseMoved
        // TODO add your handling code here:
        jLabel9.setForeground(new java.awt.Color(51,204, 255));
       
        jLabel16.setForeground(new java.awt.Color(0,0, 0));
        jLabel21.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GcomPanel1MouseMoved

    private void GcomPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MouseClicked
        // TODO add your handling code here:
         dc.setVisible(true);
          p1.setVisible(false);
        
        gco.setVisible(false);

        ip.setVisible(false);
    }//GEN-LAST:event_GcomPanel1MouseClicked

    private void GcomPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GcomPanel1MousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        this.hide();
        Authentification auth = new  Authentification();
        auth.setVisible(true);

    }//GEN-LAST:event_jLabel20MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String login =Authentification.getlogin();
                Nomclient.setText(login);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        // p1.setVisible(true);
        // gc.setVisible(false);
        //gco.setVisible(false);
        //gp.setVisible(false);
        //gf.setVisible(false);
        // ajp.setVisible(false);
        //ip.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void GcomPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel2MouseMoved
        // TODO add your handling code here:
        
         jLabel21.setForeground(new java.awt.Color(51,204, 255));
       
        jLabel16.setForeground(new java.awt.Color(0,0, 0));
        jLabel9.setForeground(new java.awt.Color(0,0, 0));
    }//GEN-LAST:event_GcomPanel2MouseMoved

    private void GcomPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel2MouseClicked
        // TODO add your handling code here:
          p1.setVisible(true);
      
        gco.setVisible(false);
        
        ip.setVisible(false);
         dc.setVisible(false);
    }//GEN-LAST:event_GcomPanel2MouseClicked

    private void GcomPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GcomPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GcomPanel2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GcomPanel;
    private javax.swing.JPanel GcomPanel1;
    private javax.swing.JPanel GcomPanel2;
    private javax.swing.JPanel Main;
    public static javax.swing.JLabel Nomclient;
    private javax.swing.JPanel PanelPrinc;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel sidePane;
    // End of variables declaration//GEN-END:variables
}
