/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import Connection.SingletonConnection;
import Menu.Menustat;
import classes.Compte;
import classes.DES;

import classes.Table;

import classes.produit;
import static classes.produit.getInfoPrd;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hp
 */
public class InformationProd extends javax.swing.JPanel {

    /**
     * Creates new form InformationProd
     */
    
    public InformationProd() {
        initComponents();
        initJcbinfoProd();
         listerDescProd();
        
      
        
    }

     
     private void listerDescProd(){
         String req = "SELECT nomProd,Description FROM produit ";
                
         
		try{
                    java.sql.Connection conn =  SingletonConnection.getConnection();
			Statement stmt = conn.createStatement();
 			stmt = conn.createStatement();
			ResultSet rs = stmt.executeQuery(req);
			
      DefaultTableModel modelDyn = Table.generateTableModel(rs);
            tblInfo.setModel(modelDyn);
           
			
			
			}catch(SQLException e){
				System.out.println("Problème durant la récupération de la liste "
                                        + "des produits");
			    System.out.println("SQLException: " + e.getMessage());
			    System.out.println("SQLState: "     + e.getSQLState());
			    System.out.println("VendorError: "  + e.getErrorCode());
			}
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCombNomProd = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(720, 460));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\info.png")); // NOI18N
        jLabel1.setText("INFORMATION SUR LE PRODUIT");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\fleche-gauche.png")); // NOI18N
        jButton1.setText(" RETOUR ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\19-magnifier-zoom-search-lineal (6).gif")); // NOI18N
        jButton2.setText("Obtenir l'info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCombNomProd.setToolTipText("");
        jCombNomProd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCombNomProdMouseMoved(evt);
            }
        });
        jCombNomProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCombNomProdMouseClicked(evt);
            }
        });
        jCombNomProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombNomProdActionPerformed(evt);
            }
        });

        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInfo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jCombNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jCombNomProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
       this.hide();
        GestionProduits gp = new GestionProduits();
        gp.setVisible(true);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCombNomProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCombNomProdActionPerformed
        // TODO add your handling code here:
      
        
        
    }//GEN-LAST:event_jCombNomProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           String nomPrd =(String)jCombNomProd.getSelectedItem();
          LinkedList<DES> l =getInfoPrd(nomPrd);
                 Vector<String>vCols=new Vector<String>();
        vCols.add("nom");
     
        vCols.add("description");
       
        //on cree notre vecteur vRows ainsi que le vecteur de vecteur vData
        Vector<Object>vRows=new Vector<Object>();
        Vector<Vector<Object>>vData=new Vector<Vector<Object>>();
        for(DES p: l){
        vRows=new Vector<Object>();//on vide
        vRows.add(p.Nom);
        vRows.add(p.Desc);
         
        //ajout au vect de vect
        vData.add(vRows);
        }
        //stat
        DefaultTableModel dyn=new DefaultTableModel(vData,vCols);
         tblInfo.setModel(dyn);
    
            
        /* ResultSet rs=null;
		try{
                     String req = "SELECT nomProd,Description FROM produit where nomProd like'% "+nomPrd+"%'";
                    java.sql.Connection conn =  SingletonConnection.getConnection();
			PreparedStatement pstmt = (PreparedStatement)conn.prepareStatement(req);
 			
			 rs = pstmt.executeQuery(req);
                        
			
      DefaultTableModel modelDyn = Table.generateTableModel(rs);
           tblInfo.setModel(modelDyn);
            
			
			
			}catch(SQLException e){
				System.out.println("Problème durant la récupération de la liste "
                                        + "des produits");
			    System.out.println("SQLException: " + e.getMessage());
			    System.out.println("SQLState: "     + e.getSQLState());
			    System.out.println("VendorError: "  + e.getErrorCode());
			}
           
      
        
      
            */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCombNomProdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombNomProdMouseMoved
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCombNomProdMouseMoved

    private void jCombNomProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCombNomProdMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jCombNomProdMouseClicked
  public static void initJcbinfoProd(){
             LinkedList<produit> lnomprod = produit.getAllPrd();
        Hashtable hnom = new Hashtable();
        for(int i=0;i<lnomprod.size();i++){
            jCombNomProd.addItem(lnomprod.get(i).nom);
            hnom.put(i, lnomprod.get(i).idP);
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JComboBox<String> jCombNomProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables
}
